development:
  adapter: postgresql
  database: venn_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: venn_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: venn_production
  host: localhost
  pool: 5
  timeout: 5000
